[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Homewood Cryo-EM"
authors = [{name = "shenping wu", email = "dummy@gmail.com"}]
dynamic = ["version", "description"]
